import Head from 'next/head'
import { Image } from '@chakra-ui/react'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta property="og:type" content="website" />
        <meta property="og:title" content="" />
        <meta property="og:description" content="" />
        <meta property="og:url" content="index.html" />
        <meta property="og:site_name" content="" />
        <meta name="twitter:description" content="" />
        <meta name="twitter:title" content="" />
      </Head>

      <main>
        <section id='mv' className={styles.mv}>
          
        </section>
      </main>
    </>
  )
}
